{% set name = "pymcdm" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymcdm-{{ version }}.tar.gz
  sha256: eada89dd87897373a0c3c82484a83a09d81564419c927c66161890b5df67da8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - pymcdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/shekhand/mcda
  summary: Python library for Multi-Criteria Decision-Making
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - mattwelborn
